"""add embedding, drop content_hash unique

Revision ID: cba35657b84e
Revises: 4301299ca86e
Create Date: 2026-10-09 17:04:43.715317

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cba35657b84e'
down_revision: str | Sequence[str] | None = '4301299ca86e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'articles',
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    )
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    # после появления дублей в процессе эксплуатации сервиса эта миграция завалится на откате - потребуется сначала почистить от дублей
    # но раз мы собираемся идти вперёд и только вперёд - не отвлекаемся
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=True)
    op.drop_column('articles', 'embedding')
    # ### end Alembic commands ###
